language: node_js
sudo: false
nodejs: "7.7"

install:
  - yarn -D
  - yarn
  - yarn global add ava

script:
  yarn test

deploy:
  provider: npm
  email: articialchamber@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true