language: node_js
sudo: false
nodejs: node

install:
  - yarn -D
  - yarn
  - yarn global add ava

script:
  yarn test

after_success:
  yarn publish

branches:
  only:
    - master 
  deploy:
    provider: npm
    email: articialchamber@gmail.com
    api_key: $NPM_TOKEN
    on: deploy-npm-release