language: node_js
sudo: false
nodejs: node

install:
  - yarn -D
  - yarn
  - yarn global add ava

before_script:
  - echo "{}" >> /tmp/vexdb.json

script:
  yarn test

deploy:
  provider: npm
  email: articialchamber@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true